### ISSUE TITLE
Moped is utilizing 'bad' Connections from the connection Pool

### ISSUE THREAD

**Issue by steve-rodriguez** [mongoid/moped#346]
I have a 3 node replica set with 1 primary and 2 secondaries.   We read from Primary.  We are using the 4.0.1 Mongoid gem, 2.0.3 Moped gem and the 2.1.1 connection pool gem.   When we directly kill a mongo node and a new Primary is selected, 'broken' connections remain in the pool and when the app grabs one it throws the ConnectionPool::ShuttingDownError.    When we gracefully step_down the primary and a new primary is selected, 'old' connections to the 'old' primary still exist in the pool and the app throws a 13435 error of "not master and slaveOK=false".    Any time a connection is 'broken' or not valid useable anymore, it should NOT be utilized by Mongoid.   Attaching screenprints of the error and the mongodb rest interface status ( for the 'killed' scenario ).   Please advise ASAP.  Thx!

![mongo issue-3](https://cloud.githubusercontent.com/assets/3719118/6071590/c4ae3006-ad54-11e4-83f5-987bfd74de15.png)
![mongo issue-2](https://cloud.githubusercontent.com/assets/3719118/6071592/c4af9cf2-ad54-11e4-882a-3ea92229db85.png)
![mongo issue-1](https://cloud.githubusercontent.com/assets/3719118/6071591/c4af42d4-ad54-11e4-850e-4084a43fe77e.png)

**Comment by dblock** [comment]
This looks like a more detailed description from https://github.com/mongoid/moped/issues/345.  @arthurnn can you please take a look? This seems new in the most recent version of moped and is affecting production for an increasing amount of people.

**Comment by dblock** [comment]
I also opened https://github.com/mongoid/moped/issues/348 which seems possibly related.

**Comment by argami** [comment]
I'm not sure how much can help, but most of my errors are related and are this:

```
A Timeout::Error occurred in background at 2015-02-07 01:02:20 UTC :

 Waited 0.5 sec
 path/shared/bundle/ruby/2.0.0/gems/connection_pool-2.0.0/lib/connection_pool/timed_stack.rb:42:in `block (2 levels) in pop'
```

I've change my pool timeout but seems to still be using 0.5

```
A Moped::Errors::ConnectionFailure occurred in users#show:

 Could not connect to a primary node for replica set #<Moped::Cluster:100465340 @seeds=[<Moped::Node resolved_address="10.101.1.100:27017">]>
 app/controllers/api/base_api_controller.rb:83:in `authenticate_user_from_token!'
```
Not sure if is because authenticate_user_from_token is the most used one but seems that the error came mainly from here. Wich is a look for a user in the db and sign_in with devise.

Two more things that can be related with the error is the way i look for the user:

```ruby
def find_by_username username
    Rails.cache.fetch(username, :expires_in => 30.seconds) do
        self.where(username: /^#{username}$/i).first
    end
end
```

**Comment by argami** [comment]
I was able to fixed, In my case i found out that the error it was 2 things.

First the pool_size, and pool_timeout wasn't enough and second, for some reason my postfix  queue was sending old messages as new ones, so from my point of view none of my modifications had any effect.

Anyways with a small pool_size and pool_timeout you should have those errors, i think that is the expected behaviour.

**Comment by dblock** [comment]
@argami What are the values you use?

**Comment by klamontagne** [comment]
This was fixed for us by #328

**Comment by argami** [comment]
@dblock this are my values:

```yaml
      options:
        pool_size: 200
        pool_timeout: 15
        retry_interval: 1
        timeout: 60
        max_retries: 20
        refresh_interval: 30
```

But beause i had a lot of noise on the mail stuff probably the last value before (100) in pool_size it was good also

Im using Puma 3 workers 0,8 threads

**Comment by mateusdelbianco** [comment]
This is fixed in #351

**Comment by dblock** [comment]
Thanks @mateusdelbianco! Looking forward to a moped release soon with these.

**Comment by mateusdelbianco** [comment]
You should thank @wandenberg for his patch! :)

**Comment by steve-rodriguez** [comment]
So are BOTH issues fixed?   The master/slave issue AND the one where the ConnectionPool gem throws the ConnectionPool::PoolShuttingDownError when you restart a VM where a mongo primary is running?     If so when will a new release of Moped be cut?   Thanks!

**Comment by niedfelj** [comment]
Please see my PR #348

**Comment by steve-rodriguez** [comment]
Still seeing this error when a mongo db node is killed.   Moped should evict this bad connection.   I am assuming since this issue is still open that this was NOT resolved with 2.0.4.   I am using Mongoid 4.0.2 and Moped 2.0.4 and Connection_Pool 2.1.1.    Any ideas when this will be addressed?  thanks!

2015-02-23T15:06:11-07:00 INFO : [ebdb5491-645e-49b7-9535-07ec2412573f] [                               10.0.32.86] [TBD] [visitor_id: 140555603] Completed 500 Internal Server E                               rror in 21ms
2015-02-23T15:06:11-07:00 FATAL : [ebdb5491-645e-49b7-9535-07ec2412573f]                                [10.0.32.86] [TBD] [visitor_id: 140555603]
ConnectionPool::PoolShuttingDownError (ConnectionPool::PoolShuttingDownEr                               ror
controller:  portfolio_summary/portfolios
action:      show
params:      {"action"=>"show", "controller"=>"portfolio_summary/portfoli                               os"}

**Comment by michaelrobinette** [comment]
Still seeing it with Moped 2.0.4 as well

**Comment by steve-rodriguez** [comment]
To provide more information on this issue, I have a 3 node replica set ( node1, node2 and node3 ).   Node1 is the primary.   When node2 (secondary node ) is shutdown via the instructions on Mongodbs website for upgrading a replicaset,  Mongoid/Moped throws a ConnectionPool::PoolShuttingDownError when it attempts to grab a connection.   WHY would it throw this error if this error is generated from a SECONDARY node that should NOT be in the pool anyway????   The mongoid.yml default read option is primary.    It should never be creating pool connections to SECONDARY nodes.    It appears to me that Mongoid/Moped is throwing SECONDARY node exceptions to the client when the read preference is PRIMARY.   And if this error is thrown from logic that is monitoring the replica set, it should NEVER be returned to the client.   Mongoid/Moped should always return a connection to the PRIMARY node if the primary node is UP and AVAILABLE.    Seems like a fairly MAJOR bug.

**Comment by niedfelj** [comment]
@steve-rodriguez 

Can you try it using my branch and let me know the results?  I've added more logging to moped and integrated a few pull requests that have not been integrated into Moped master/gem.  We are using this in production without issue, although there are still some wonky things with IP changes etc:

```
gem 'moped', :git=>'git://github.com/niedfelj/moped.git', :branch=>'all_patches'
```

**Comment by steve-rodriguez** [comment]
Will do.   Thx.

**Comment by fedenusy** [comment]
@niedfelj I tried your `all_patches` branch on prod and still got tons of `Moped::Errors::ConnectionFailure: Could not connect to a primary node for replica set` :(

**Comment by steve-rodriguez** [comment]
@niedfelj I tried this branch and it appears the ConnectionPool::PoolShuttingDownError has gone away, BUT when stepping down the primary, I see these errors now:

Moped::Errors::ConnectionFailure (Could not connect to a primary node for replica set #<Moped::Cluster:1553548 @seeds=[<Moped::Node resolved_address="ip1:33478">, <Moped::Node resolved_address="ip2:33478">, <Moped::Node resolved_address="ip3:33478">]>

where ip1, ip2 and ip3 are our internal ipaddresses for each Mongodb node in the replica set.

So to test, I had our DBAs shutdown each secondary node independently and restart them.   I saw no connection pool shutting down errors.   I then had all nodes online, and had them do a stepdown for the primary node.    Then  I started getting the Could not connect to primary node in the replica set.   Version 2.0.4 of Moped appears to have solved this issue, but your branch/patches contains the could not connect to primary issue I believe.    Please advise.   Thanks for your help!  I think this is getting closer to working...   So I think if you merge your changes with the 2.0.4 changes, we may have something that is close to working...

**Comment by fedenusy** [comment]
@steve-rodriguez moped 2.0.4 without @niedfelj's patch also throws `Moped::Errors::ConnectionFailure: Could not connect to a primary node`. So I'm not sure that merging 2.0.4 into @niedfelj's branch will do the trick.

**Comment by steve-rodriguez** [comment]
The 2.0.4 branch does throws those, BUT it actually does reconnect when retrying I believe.   I will do some more testing to verify

**Comment by steve-rodriguez** [comment]
Ok, heres the scoop to reproduce this issues.  You have a 3 node replicaset ( n1-primary, n2-secondary and n3-secondary )

TEST1 - Good Behavior:    If you have just restarted your app and have ALL good connections in your connection pool, you can do an rs.stepDown() to elect a new primary.   The app will work properly and you get no errors.    

BUT, if you do a shutdown of one of the secondaries ( n2 ) and then restart it, AND then do an rs.stepDown(), where n2 is now the primary ( n2-primary, n1-secondary, n3-secondary ), it will attempt to talk to the primary and will throw the Moped::Errors::ConnectionFailure: Could not connect to a primary node error.    I have my number of retries set to 20 and I can see it count down retrying every second and then it fails after 20 tries.  So I suspect that somehow moped is mistakenly keeping around connections that still think that n1 is primary when it actually is now a secondary.

**Comment by steve-rodriguez** [comment]
@niedfelj @fedenusy @durran .   Please advise on my prior comments.  Thanks!

**Comment by wandenberg** [comment]
Hi @steve-rodriguez , I'm trying to reproduce the problem and solve it but I wasn't able to.
I fixed a problem with retry after a setpDown, but didn't have this scenario of shutdown + stepDown.
Can you help me reproduce it? 
When you say 3 nodes they have to be on different servers/vm or can be 3 mongod instances on same machine?
Which value are you using for pool_size?
By shutdown you mean kill signal, kill -9, shutdown command ...?
Which version of mongodb are you using?
With or without authentication?

**Comment by steve-rodriguez** [comment]
@wandenberg Here is our environment:

1)  3 nodes ( 1 primary and 2 secondaries ) on 3 different RHEL vms
2)  pool_size for testing purposes is 10.   I can make it larger but it doesn't solve the issue.   I made it 10 so I can easily reproduce the issue.
3) shutdown command
4) 2.6.6 of Mongodb
5) No authentication

Here is my Mongoid.yml settings:
production:
  sessions:
    default:
      database: edist
      hosts:
        ['web-node-db1:33478','web-node-db2:33478', 'web-node-db3:33478']
      options:
        pool_size: 10
        pool_timeout: 15
        retry_interval: 1
        timeout: 30
        max_retries: 20
        refresh_interval: 20

    secondary:
      database: fund
      hosts:
        ['cms-node-db1:33478','cms-node-db2:33478', 'cms-node-db3:33478']
      options:
        pool_size: 10
        pool_timeout:15
        retry_interval: 1
        timeout: 30
        max_retries: 20
        refresh_interval: 20

If you need anything else, let me know..  Will be doing more testing today to see if I can further isolate the issue.. Thanks!  -Steve

**Comment by steve-rodriguez** [comment]
Here are some screen prints of the steps to reproduce the issue.   Read preference is primary.    Hope my description and screen prints help.

Each screen print starts with a number corresponding to the 7 steps in sequential order to reproduce the issue.   I think that somehow Moped is creating pool connections to the secondary node, but ONLY gives back a connection(s) to the Primary node.   I believe that moped keeps track of the 3 nodes ( 1 primary and 2 secondary ).   when a secondary is brought down, all is good as Moped is reading from the primaries.   But somehow moped keeps state that the secondary node is unavailable.   When the secondary node is brought back up, all is good as it is still a secondary node.    Once you do a stepDown and that secondary node that was JUST down becomes primary,  you start seeing occassional issues where it can not connect to the Primary node.   I think this occurs when moped returns a connection that was ORIGINALLY a connection to the secondary, but now that node is primary, but since is was brought down, the status of the node remains down I believe.

![4 - stepdown_primary node 3](https://cloud.githubusercontent.com/assets/3719118/6493448/fb34186a-c277-11e4-8a03-4a1359b3fab8.png)
![5 - node - 2 elected primary](https://cloud.githubusercontent.com/assets/3719118/6493451/fb3443d0-c277-11e4-82e0-264d170cacc3.png)
![6 - moped trying to connect to node 2](https://cloud.githubusercontent.com/assets/3719118/6493450/fb34439e-c277-11e4-9695-d2e3012aeaa7.png)
![7 - eventual could not connect to primary error](https://cloud.githubusercontent.com/assets/3719118/6493449/fb341ab8-c277-11e4-8d82-07fda73b0fc9.png)
![1 - initial_state](https://cloud.githubusercontent.com/assets/3719118/6493452/fb3458ca-c277-11e4-8985-b4b7cac3f742.png)
![2 - shutdown node 2 - secondary](https://cloud.githubusercontent.com/assets/3719118/6493453/fb363d3e-c277-11e4-96c6-5d42449fe949.png)
![3 - bring-up-secondary](https://cloud.githubusercontent.com/assets/3719118/6493454/fb4248f4-c277-11e4-9b89-25f40cc8853d.png)

**Comment by niedfelj** [comment]
Can you make sure you have your Rails logger set to debug and make sure Moped/Mongoid are setup like this in an initializer:

```
Mongoid.logger = Rails.logger
Moped.logger = Rails.logger
```
You should be able to see MOPED asking for primaries, which I don't see in your output:

```
MOPED: 172.169.54.93:6210 COMMAND      database=admin command={:ismaster=>1} runtime: 1.3853ms
```

I'm also running a separate version of Mongoid, because I wanted to be able to see the exceptions during operations, which both mongoid/moped often just swallow:

https://github.com/mongoid/mongoid/pull/3884/files

I would set your pool_timeout to 0.5 ... 15 is too high and it's only the setting for "checking out" a connection (not connecting or making a connection).

And refresh_interval should be higher also...I would set it to at least 120 (the default is 300)

And I would lower timeout to 5.

I have this PR out for showing more configs (you may be interested in tuning down_interval)

https://github.com/mongoid/mongoid-site/pull/254/files

**Comment by steve-rodriguez** [comment]
@niedfelj Will do this today and let you know the results and will post some log files..

**Comment by wandenberg** [comment]
Hi @steve-rodriguez 

Can you test the code at this [branch](https://github.com/wandenberg/moped/tree/debug_for_issue_346) on your server?
Be sure that the moped-2.0.4.1.gem was generated.

It will produce some log messages like these bellow.
Maybe  this branch does not solve the problem, but the log messages will help me try to fix the problem.

```
W, [2015-03-06T17:18:26.081014 #8846]  WARN -- :   MOPED: Getting configuration for node #<Moped::Node:0x00000003a8ed20>, configuration: {"setName"=>"dev", "setVersion"=>1, "ismaster"=>false, "secondary"=>true, "hosts"=>["localhost:27117", "localhost:27317", "localhost:27217"], "primary"=>"localhost:27217", "me"=>"localhost:27117", "maxBsonObjectSize"=>16777216, "maxMessageSizeBytes"=>48000000, "maxWriteBatchSize"=>1000, "localTime"=>2015-03-06 20:18:26 UTC, "maxWireVersion"=>2, "minWireVersion"=>0, "ok"=>1.0}. runtime: n/a
W, [2015-03-06T17:18:26.082225 #8846]  WARN -- :   MOPED: connection failure investigation: failed with class 'Moped::Errors::OperationFailure' and message 'The operation: #<Moped::Protocol::Command
  @length=80
  @request_id=7
  @response_to=0
  @op_code=2004
  @flags=[]
  @full_collection_name="test_db.$cmd"
  @skip=0
  @limit=-1
  @selector={:getlasterror=>1, :w=>"majority"}
  @fields=nil>
failed with error 10058: "not master"

See https://github.com/mongodb/mongo/blob/master/docs/errors.md
for details about this error.'. runtime: n/a
W, [2015-03-06T17:18:26.082284 #8846]  WARN -- :   MOPED: Retrying connection attempt 30 more time(s). runtime: n/a
W, [2015-03-06T17:18:27.083077 #8846]  WARN -- :   MOPED: Getting configuration for node #<Moped::Node:0x00000003a8ed20>, configuration: {"setName"=>"dev", "setVersion"=>1, "ismaster"=>false, "secondary"=>true, "hosts"=>["localhost:27117", "localhost:27317", "localhost:27217"], "me"=>"localhost:27117", "maxBsonObjectSize"=>16777216, "maxMessageSizeBytes"=>48000000, "maxWriteBatchSize"=>1000, "localTime"=>2015-03-06 20:18:27 UTC, "maxWireVersion"=>2, "minWireVersion"=>0, "ok"=>1.0}. runtime: n/a
W, [2015-03-06T17:18:27.083978 #8846]  WARN -- :   MOPED: Getting configuration for node #<Moped::Node:0x00000003a8e780>, configuration: {"setName"=>"dev", "setVersion"=>1, "ismaster"=>false, "secondary"=>true, "hosts"=>["localhost:27217", "localhost:27317", "localhost:27117"], "me"=>"localhost:27217", "maxBsonObjectSize"=>16777216, "maxMessageSizeBytes"=>48000000, "maxWriteBatchSize"=>1000, "localTime"=>2015-03-06 20:18:27 UTC, "maxWireVersion"=>2, "minWireVersion"=>0, "ok"=>1.0}. runtime: n/a
W, [2015-03-06T17:18:27.084718 #8846]  WARN -- :   MOPED: Getting configuration for node #<Moped::Node:0x00000003a8e230>, configuration: {"setName"=>"dev", "setVersion"=>1, "ismaster"=>false, "secondary"=>true, "hosts"=>["localhost:27317", "localhost:27217", "localhost:27117"], "me"=>"localhost:27317", "maxBsonObjectSize"=>16777216, "maxMessageSizeBytes"=>48000000, "maxWriteBatchSize"=>1000, "localTime"=>2015-03-06 20:18:27 UTC, "maxWireVersion"=>2, "minWireVersion"=>0, "ok"=>1.0}. runtime: n/a
W, [2015-03-06T17:18:27.085048 #8846]  WARN -- :   MOPED: Refreshed none #<Moped::Node:0x00000003a8ed20>, primary: false refreshed_at: 2015-03-06 17:18:27 -0300. runtime: n/a
W, [2015-03-06T17:18:27.085095 #8846]  WARN -- :   MOPED: Refreshed none #<Moped::Node:0x00000003a8e780>, primary: false refreshed_at: 2015-03-06 17:18:27 -0300. runtime: n/a
W, [2015-03-06T17:18:27.085136 #8846]  WARN -- :   MOPED: Refreshed none #<Moped::Node:0x00000003a8e230>, primary: false refreshed_at: 2015-03-06 17:18:27 -0300. runtime: n/a
W, [2015-03-06T17:18:27.085274 #8846]  WARN -- :   MOPED: connection failure investigation: failed with class 'Moped::Errors::ConnectionFailure' and message 'Could not connect to a primary node for replica set #<Moped::Cluster:30701240 @seeds=[<Moped::Node resolved_address="127.0.0.1:27117">, <Moped::Node resolved_address="127.0.0.1:27217">, <Moped::Node resolved_address="127.0.0.1:27317">]>'. runtime: n/a
```

**Comment by steve-rodriguez** [comment]
@wandenberg Yep give me a bit and I will post the results.   Didn't have a chance to post results yesterday...

**Comment by steve-rodriguez** [comment]
@wandenberg Your branch has bugs in it and isn't even functional...  If you want me to test with it, please fix the bugs.  Thx...

NoMethodError (private method `warn' called for nil:NilClass


controller:  articles
action:      index
params:      {"action"=>"index", "controller"=>"articles"}
headers:     ["ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8\n", "ACCEPT_ENCODING: gzip, deflate, sdch\n", "ACCEPT_LANGUAGE: en-US,en;q=0.8\n", "CONNECTION: keep-alive\n", "COOKIE: visitor_id=141450813; AMCV_oppenheimerfunds%40AdobeOrg=-1506950487%7CMCMID%7C75905084433512300062483669319620107083%7CMCAAMLH-1426280307%7C9%7CMCAID%7CNONE; s_vnum=1427868000758%26vn%3D2; __atuvc=2%7C9\n", "HOST: localhost:3000\n", "USER_AGENT: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.76 Safari/537.36\n", "VERSION: HTTP/1.1\n"]
message:     
server:      localhost:3000
remote_ip:   127.0.0.1
referrer:    
HTTP method: GET
request URL: http://localhost:3000/investors/articles
request body (text/plain, 0 bytes): []
start time:  2015-03-09T08:19:55-06:00
end time:    2015-03-09T08:19:56-06:00
duration:    1.361 seconds
user agent:  Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.76 Safari/537.36
status:      500
):



  C:/DEV/programs/jruby/lib/ruby/gems/shared/bundler/gems/moped-cdefb4aba90c/lib/moped/loggable.rb:56:in `warn'
  C:/DEV/programs/jruby/lib/ruby/gems/shared/bundler/gems/moped-cdefb4aba90c/lib/moped/node.rb:548:in `configure'
  C:/DEV/programs/jruby/lib/ruby/gems/shared/bundler/gems/moped-cdefb4aba90c/lib/moped/node.rb:432:in `refresh'
  C:/DEV/programs/jruby/lib/ruby/gems/shared/bundler/gems/moped-cdefb4aba90c/lib/moped/cluster.rb:188:in `refresh'
  org/jruby/RubyArray.java:1613:in `each'
  C:/DEV/programs/jruby/lib/ruby/gems/shared/bundler/gems/moped-cdefb4aba90c/lib/moped/cluster.rb:200:in `refresh'
  C:/DEV/programs/jruby/lib/ruby/gems/shared/bundler/gems/moped-cdefb4aba90c/lib/moped/cluster.rb:151:in `nodes'
  C:/DEV/programs/jruby/lib/ruby/gems/shared/bundler/gems/moped-cdefb4aba90c/lib/moped/cluster.rb:246:in `with_primary'
  C:/DEV/programs/jruby/lib/ruby/gems/shared/bundler/gems/moped-cdefb4aba90c/lib/moped/read_preference/primary.rb:55:in `with_node'
  org/jruby/RubyProc.java:290:in `call'
  org/jruby/RubyProc.java:271:in `call'
  C:/DEV/programs/jruby/lib/ruby/gems/shared/bundler/gems/moped-cdefb4aba90c/lib/moped/retryable.rb:30:in `with_retry'
  C:/DEV/programs/jruby/lib/ruby/gems/shared/bundler/gems/moped-cdefb4aba90c/lib/moped/read_preference/primary.rb:54:in `with_node'
  C:/DEV/programs/jruby/lib/ruby/gems/shared/bundler/gems/moped-cdefb4aba90c/lib/moped/cursor.rb:136:in `load_docs'
  mongoid (4.0.2) lib/mongoid/query_cache.rb:234:in `load_docs'
  mongoid (4.0.2) lib/mongoid/query_cache.rb:135:in `with_cache'
  mongoid (4.0.2) lib/mongoid/query_cache.rb:234:in `load_docs'
  C:/DEV/programs/jruby/lib/ruby/gems/shared/bundler/gems/moped-cdefb4aba90c/lib/moped/cursor.rb:27:in `each'
  C:/DEV/programs/jruby/lib/ruby/gems/shared/bundler/gems/moped-cdefb4aba90c/lib/moped/query.rb:78:in `each'
  mongoid (4.0.2) lib/mongoid/contextual/mongo.rb:122:in `each'
  org/jruby/RubyEnumerable.java:763:in `map'
  mongoid (4.0.2) lib/mongoid/contextual/mongo.rb:255:in `map'
  C:0:in `map'
  C:/DEV/rails_apps/branches/investors_trunk_new_connection_pool_gem/app/controllers/articles_controller.rb:5:in `index'

**Comment by steve-rodriguez** [comment]
@niedfelj Here is a RECAP of my testing with your branch with the following mongoid.yml settting:

production:
  sessions:
    default:
      database: edist
      hosts:
        ['qa2-web-db1:33478', 'qa2-web-db2:33478', 'qa2-web-db3:33478']
      options:
        read: primary_preferred
        pool_size: 10
        pool_timeout: 0.5
        retry_interval: 1
        timeout: 5
        max_retries: 20
        refresh_interval: 120

    secondary:
      database: fund
      hosts:
        ['qa2-cms-db1:33478', 'qa2-cms-db2:33478', 'qa2-cms-db3:33478']
      options:
        read: primary_preferred
        pool_size: 10
        pool_timeout: 0.5
        retry_interval: 1
        timeout: 5
        max_retries: 20
        refresh_interval: 120
------------------------------------------------------------

I changed my read preference to be primary_preferred.    Ideally a read preference of primary should work, but I believe something in moped caused it to NOT work.    I had a 3 node replicaset that looks like this to start ( n1-secondary, n2-primary and n3-secondary ).    I brought down n1 and tested for a bit with no errors available to the app, but moped errors in the log which is fine.  I brought n1 back up and took down n3.    Same behavior.   I brought n3 back up and stepped down n2.   Then I took down n2 and brought it back up.   All of this was done to simulate doing a mongo db upgrade.   No errors visible to the app, but the attached moped errors occurred in the log.   I started the test at 1:34 p.m. and ended it around 1:38 p.m.    

Please advise on this TEST and getting your niedfelj branch changes into the main Moped code base and a NEW release cut.    It would be nice if the read preference could be primary instead of primary_preferred.    Thanks!  -Steve
![moped_errors](https://cloud.githubusercontent.com/assets/3719118/6563285/8cf627de-c665-11e4-8c2d-55445a0f6153.png)

**Comment by wandenberg** [comment]
Hi @steve-rodriguez 

at some point on your application the logger was set to nil and the Moped.logger do not create the default logger again.
You can test this doing inside the console something like that
```
Moped.logger # will return a logger instance, Rails logger or Logger
Moped.logger = nil
Moped.logger # will return nil
```
I changed the Moped.logger to always return an instance.
Doing the same test with this 27cb9948ede9961a12d3f2d96f04d98ca33cfa66 the final call will return at least a Logger instance.

Sorry for the problem I could have caused.

**Comment by wandenberg** [comment]
Hi @steve-rodriguez 

did you have opportunity to test the code?

**Comment by steve-rodriguez** [comment]
@wandenberg Sorry for the delay.   I had to get some QA resources to help test and they were unavailable at the end of last week.  Will be doing some testing today and respond by the end of the day.  thx!

**Comment by steve-rodriguez** [comment]
@wandenberg Here is a snippet of my mongoid.yml and the log file from the app that shows the ConnectionPool::PoolShuttingDownError.   All I basically did to generate this error was shut down a secondary node in the replica set and then clicked around the app a few times and this error would show up occasionally.

Mongoid.yml snippet:

production:
  sessions:
    default:
      database: edist
      hosts:
        ['qa2-web-db1:33478', 'qa2-web-db2:33478', 'qa2-web-db3:33478']
      options:
        read: primary
        pool_size: 10
        pool_timeout: 0.5
        retry_interval: 1
        timeout: 5
        max_retries: 20
        refresh_interval: 120

    secondary:
      database: fund
      hosts:
        ['qa2-cms-db1:33478', 'qa2-cms-db2:33478', 'qa2-cms-db3:33478']
      options:
        read: primary
        pool_size: 10
        pool_timeout: 0.5
        retry_interval: 1
        timeout: 5
        max_retries: 20
        refresh_interval: 120


[jruby_rack.txt | uploaded via ZenHub](https://files.zenhub.io/55073316a564ab7a3147be92)

**Comment by steve-rodriguez** [comment]
@niedfelj Any feedback on what I mentioned to you 8 days ago?  thanks!

**Comment by niedfelj** [comment]
@steve-rodriguez Those log messages aren't necessarily "errors".  I just expanded the logging facilities in my branch because I wanted to have more visibility into the processes occurring in moped/mongoid (IMHO, the current implementations take the stance of showing almost no logging, and that's not helpful).  I'm glad my branch worked for you, unfortunately I don't have any ability to get them into the main codebase.  My PR's are sitting there waiting...

**Comment by dblock** [comment]
Bump @durran @arthurnn.

**Comment by wandenberg** [comment]
Hi @steve-rodriguez 

can you test the code on this #359 ?
I think this will solve the problem with ConnectionPool::PoolShuttingDownError.
If it works and you need retry for write operations you can test this other [branch](https://github.com/wandenberg/moped/tree/operation_timeout).

**Comment by aponsin** [comment]
Are there any progress on this issue? It's really a plague for production application running with it. Thx @steve-rodriguez @niedfelj @wandenberg for the work and please @durran @arthurnn could we incorporate the fixes into a new release ASAP ? Thx.

**Comment by dblock** [comment]
The little bird tells me we're going to get relatively little support for this because Mongoid 5 + the office MongoDB Ruby driver 2.0 are in a fairly advanced shape. It does seem like @arthurnn is willing to merge commits though and release things - lets all try to give him some PRs he can vote yes/no to?

**Comment by matsimitsu** [comment]
We're seeing this issue as well when one of the secondaries is not reachable at all (this is with `2.0.4` and the patches from @wandenberg in the `wandenberg/operation_timeout` branch. ) 

To reproduce (in a 3 node replicaset) 
simply shutdown one of the secondaries (the entire host, not just Mongod) and you'll see:

```
2015-04-29T14:25:01.841Z 27232 TID-otcy5hal8 WARN: ConnectionPool::PoolShuttingDownError
2015-04-29T14:25:01.842Z 27232 TID-otcy5hal8 WARN: /home/app/vendor/bundle/ruby/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:78:in `block (2 levels) in pop'
```

When running this in Sidekiq, it won't recognise this as an error and drop the job completely, causing lost data from the queue.

**Comment by matsimitsu** [comment]
So I did a little digging today and this is the relevant Stack:

```
2015-04-30T10:59:24.371Z 24905 TID-ow5881u84 WARN: ConnectionPool::PoolShuttingDownError
2015-04-30T10:59:24.371Z 24905 TID-ow5881u84 WARN: /home/app/releases/6c1b2cea61f123c5d3298eb4f75c06f015cf3c6c/vendor/bundle/ruby/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:78:in `block (2 levels) in pop'
/home/app/releases/6c1b2cea61f123c5d3298eb4f75c06f015cf3c6c/vendor/bundle/ruby/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:77:in `loop'
/home/app/releases/6c1b2cea61f123c5d3298eb4f75c06f015cf3c6c/vendor/bundle/ruby/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:77:in `block in pop'
/home/app/releases/6c1b2cea61f123c5d3298eb4f75c06f015cf3c6c/vendor/bundle/ruby/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:76:in `synchronize'
/home/app/releases/6c1b2cea61f123c5d3298eb4f75c06f015cf3c6c/vendor/bundle/ruby/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:76:in `pop'
/home/app/releases/6c1b2cea61f123c5d3298eb4f75c06f015cf3c6c/vendor/bundle/ruby/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:89:in `checkout'
/home/app/releases/6c1b2cea61f123c5d3298eb4f75c06f015cf3c6c/vendor/bundle/ruby/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:61:in `block in with'
/home/app/releases/6c1b2cea61f123c5d3298eb4f75c06f015cf3c6c/vendor/bundle/ruby/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt'
/home/app/releases/6c1b2cea61f123c5d3298eb4f75c06f015cf3c6c/vendor/bundle/ruby/2.2.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
/home/app/releases/6c1b2cea61f123c5d3298eb4f75c06f015cf3c6c/vendor/bundle/ruby/2.2.0/bundler/gems/moped-4990ec2a8fab/lib/moped/node.rb:116:in `connection'
/home/app/releases/6c1b2cea61f123c5d3298eb4f75c06f015cf3c6c/vendor/bundle/ruby/2.2.0/bundler/gems/moped-4990ec2a8fab/lib/moped/node.rb:147:in `disconnect'
/home/app/releases/6c1b2cea61f123c5d3298eb4f75c06f015cf3c6c/vendor/bundle/ruby/2.2.0/bundler/gems/moped-4990ec2a8fab/lib/moped/failover/retry.rb:27:in `execute'
/home/app/releases/6c1b2cea61f123c5d3298eb4f75c06f015cf3c6c/vendor/bundle/ruby/2.2.0/bundler/gems/moped-4990ec2a8fab/lib/moped/node.rb:193:in `rescue in ensure_connected'
/home/app/releases/6c1b2cea61f123c5d3298eb4f75c06f015cf3c6c/vendor/bundle/ruby/2.2.0/bundler/gems/moped-4990ec2a8fab/lib/moped/node.rb:196:in `ensure_connected'
/home/app/releases/6c1b2cea61f123c5d3298eb4f75c06f015cf3c6c/vendor/bundle/ruby/2.2.0/bundler/gems/moped-4990ec2a8fab/lib/moped/node.rb:598:in `block in flush'
/home/app/releases/6c1b2cea61f123c5d3298eb4f75c06f015cf3c6c/vendor/bundle/ruby/2.2.0/bundler/gems/moped-4990ec2a8fab/lib/moped/node.rb:626:in `block in logging'
/home/app/releases/6c1b2cea61f123c5d3298eb4f75c06f015cf3c6c/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.7/lib/active_support/notifications.rb:159:in `block in instrument'
/home/app/releases/6c1b2cea61f123c5d3298eb4f75c06f015cf3c6c/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.7/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/app/releases/6c1b2cea61f123c5d3298eb4f75c06f015cf3c6c/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.7/lib/active_support/notifications.rb:159:in `instrument'
/home/app/releases/6c1b2cea61f123c5d3298eb4f75c06f015cf3c6c/vendor/bundle/ruby/2.2.0/bundler/gems/moped-4990ec2a8fab/lib/moped/instrumentable.rb:31:in `instrument'
/home/app/releases/6c1b2cea61f123c5d3298eb4f75c06f015cf3c6c/vendor/bundle/ruby/2.2.0/bundler/gems/moped-4990ec2a8fab/lib/moped/node.rb:625:in `logging'
/home/app/releases/6c1b2cea61f123c5d3298eb4f75c06f015cf3c6c/vendor/bundle/ruby/2.2.0/bundler/gems/moped-4990ec2a8fab/lib/moped/node.rb:596:in `flush'
/home/app/releases/6c1b2cea61f123c5d3298eb4f75c06f015cf3c6c/vendor/bundle/ruby/2.2.0/bundler/gems/moped-4990ec2a8fab/lib/moped/node.rb:399:in `process'
/home/app/releases/6c1b2cea61f123c5d3298eb4f75c06f015cf3c6c/vendor/bundle/ruby/2.2.0/bundler/gems/moped-4990ec2a8fab/lib/moped/operation/read.rb:48:in `execute'
/home/app/releases/6c1b2cea61f123c5d3298eb4f75c06f015cf3c6c/vendor/bundle/ruby/2.2.0/bundler/gems/moped-4990ec2a8fab/lib/moped/node.rb:657:in `read'
/home/app/releases/6c1b2cea61f123c5d3298eb4f75c06f015cf3c6c/vendor/bundle/ruby/2.2.0/bundler/gems/moped-4990ec2a8fab/lib/moped/node.rb:90:in `command'
/home/app/releases/6c1b2cea61f123c5d3298eb4f75c06f015cf3c6c/vendor/bundle/ruby/2.2.0/bundler/gems/moped-4990ec2a8fab/lib/moped/node.rb:440:in `refresh'
/home/app/releases/6c1b2cea61f123c5d3298eb4f75c06f015cf3c6c/vendor/bundle/ruby/2.2.0/bundler/gems/moped-4990ec2a8fab/lib/moped/cluster.rb:188:in `block in refresh'
/home/app/releases/6c1b2cea61f123c5d3298eb4f75c06f015cf3c6c/vendor/bundle/ruby/2.2.0/bundler/gems/moped-4990ec2a8fab/lib/moped/cluster.rb:200:in `each'
/home/app/releases/6c1b2cea61f123c5d3298eb4f75c06f015cf3c6c/vendor/bundle/ruby/2.2.0/bundler/gems/moped-4990ec2a8fab/lib/moped/cluster.rb:200:in `refresh'
/home/app/releases/6c1b2cea61f123c5d3298eb4f75c06f015cf3c6c/vendor/bundle/ruby/2.2.0/bundler/gems/moped-4990ec2a8fab/lib/moped/cluster.rb:151:in `nodes'
/home/app/releases/6c1b2cea61f123c5d3298eb4f75c06f015cf3c6c/vendor/bundle/ruby/2.2.0/bundler/gems/moped-4990ec2a8fab/lib/moped/cluster.rb:246:in `with_primary'
```

The issue lies in the retry beeing attempted when a node is down, (I use the @wandenberg debug branch to add even more logging. 

```
W, [2015-04-30T11:21:02.112642 #1386]  WARN -- :   MOPED: Failover strategy source: 'Moped::Errors::ConnectionFailure' and message 'Timed out connection to Mongo on xxx.xxx.xxx.85:27017'. runtime: n/a
W, [2015-04-30T11:21:02.113800 #1386]  WARN -- :   MOPED:  Disconnecting from <Moped::Node resolved_address="xxx.xxx.xxx.85:27017"> #<Moped::Node:0x007fdd3b7cf900> runtime: n/a
W, [2015-04-30T11:21:02.122444 #1386]  WARN -- :   MOPED: Getting configuration for node #<Moped::Node:0x007fdd3b7cf1d0>, configuration: {"setName"=>"staging", "setVersion"=>7, "ismaster"=>false, "secondary"=>true, "hosts"=>["mongo3.staging:27017", "mongo1.staging:27017", "mongo2.staging:27017"], "primary"=>"mongo1.staging:27017", "me"=>"mongo3.staging:27017", "maxBsonObjectSize"=>16777216, "maxMessageSizeBytes"=>48000000, "maxWriteBatchSize"=>1000, "localTime"=>2015-04-30 11:21:02 UTC, "maxWireVersion"=>2, "minWireVersion"=>0, "ok"=>1.0}. runtime: n/a
```

The retry fails, because it tries to disconnect the node form a connection that is already beeing shutdown. 

When I change the Failover strategy (lib/moped/failover.rb) from: 
```
Errors::ConnectionFailure => Retry,
```
 to
```
Errors::ConnectionFailure => Disconnect,
``` 

The issue disappears.

I tried rescue-ing the connection pool error, but I had little luck

(lib/moped/failover/retry.rb)
```
def execute(exception, node)
        begin
          node.disconnect unless exception.is_a?(Errors::PoolTimeout)
        rescue => e
          node.down!
          raise(e)
        end

        begin
          node.connection do |conn|
            yield(conn) if block_given?
          end
        rescue Errors::PoolTimeout => e
          raise Errors::ConnectionFailure.new e
        rescue Exception => e
          node.down!
          raise(e)
        end
      end
```
It would still raise the connectionpool error. 

So my question is, why would we want to retry the `Moped::Errors::ConnectionFailure`? Isn't it better to just disconnect and after the `refresh_interval` in the moped config it would try again right?

**Comment by sahin** [comment]
+1, @arthurnn any update on this one?

**Comment by sahin** [comment]
+1 

right now, we have a some issues in productions in dozens of server and websites + api that is used by many vendors, movie studios and our apps.

Right now, if any thing happens to a node in the replication , we are getting 
No route to host - connect(2) for "20.0.0.16" port 27017
ConnectionPool::PoolShuttingDownError

**Comment by sahin** [comment]
@steve-rodriguez , @matsimitsu solution seems fair, what is the final say? it will be great if we can merge and dump the version

**Comment by steve-rodriguez** [comment]
@arthurnn @durran @sahin @matsimitsu As you can see, I have been pushing to get this fixed for months and for some reason there seems to be no activity on this project with respect to this issue and getting various pull requests committed.   Quite a few developers have provided potential solutions, but there seems to be nothing getting pulled into the code base.   Can one of the committers address this issue and why there seems to be no pull requests or ideas being committed/implemented?  Thanks!

**Comment by sahin** [comment]
@arthurnn @durran , the moped is in production and powering some super famous movie sites, I cant tell which one, but I can give hints, skynet :) , so can go and check the site and use movielala.com logo in the videos. So I can say there are so many people all over the world is affecting from this issue. It is also affecting our production api + web site.

I know that you guys are busy and moped is moving to offical mongo support :) but before that. 

We are having crazy issues with this error , it will be super great. You guys can consider @steve-rodriguez 's solution and other solutions.

**Comment by sahin** [comment]
@arthurnn @durran @matsimitsu @steve-rodriguez , I just had around 10 K errors during the primary election.

![errors bugsnag](https://cloud.githubusercontent.com/assets/2508980/7781877/ec738060-00af-11e5-8a98-96ab53076c92.png)

**Comment by sahin** [comment]
@arthurnn @durran @matsimitsu @steve-rodriguez any updates?

**Comment by isair** [comment]
+1

**Comment by deepredsky** [comment]
Bump! @durran @arthurnn

**Comment by equuleus** [comment]
+1

**Comment by dblock** [comment]
Can everyone comment on what they are running in production right now (and with what effect)? Maybe you can push a version of the moped gem to Rubygems under a different name (eg. moped-pool-shutting-down-fixes)?

**Comment by dblock** [comment]
https://github.com/mongoid/moped/pull/351 has been merged, can people on this thread please try that solution?

**Comment by steve-rodriguez** [comment]
@dblock Didn't get a chance to get to this yesterday.  Will test it this afternoon and provide feedback.  Thanks!

**Comment by chenqiangzhishen** [comment]
use @argami refer config seems not appear the issue `Moped::Errors::ConnectionFailure: Could not connect to a primary nod...` again.
